import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";

const notoSansThai = localFont({
  src: [
    {
      path: "./fonts/NotoSansThai-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/NotoSansThai-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${notoSansThai.className} antialiase`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          {/* <main className="container mx-auto max-w-7xl top-0"> */}
          <main className="">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
